### ISSUE TITLE
Creación de un índice e indexarlo

### ISSUE THREAD

**Issue by mrcodedev** [mrcodedev/frontend-developer-resources#3]
Crear un índice e indexarlo para que sea más fácil navegar entre las secciones

**Comment by mrcodedev** [comment]
Gracias a @metatron18es, ya tenemos índice. Millones de gracias

**Comment by mrcodedev** [comment]
Abro de nuevo la issue porque tengo que revisar que funcione bien. Estoy en el iPad y no sé por qué no enlaza bien.

**Comment by soniatechie** [comment]
Sobre los links en Safari, aparentemente los que tienen accentos no funcionan bien...
He visto aquí (https://docs.microsoft.com/es-es/contribute/how-to-write-links) que se puede poner un ancor para poner un id sin acentos, pero también dice que no es recomendable... No lo he probado

`## <a id="anchortext" />Header text`

**Comment by metatron18es** [comment]
He visto aquí (https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown) que recomiendan usar mas el `## <a name="anchortext" /> Header text`
He hecho alguna prueba en una rama a parte y si que parece que va.
Gracias por la ayuda!

**Comment by mrcodedev** [comment]
Cierro issue, se cierra con la PR #6 👍
